import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import HomeMain from "@/components/homemain";
import { EventsData } from "@/types";

const inter = Inter({ subsets: ["latin"] });
 type Props = {
  data: EventsData["events_categories"];
}

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeMain data={data} />
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
