import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import HomeMain from "@/components/homemain";
import Footer from "@/components/footer";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });
 type Props = {
  data: {
    id: string;
    title: string;
    description: string;
    image: string;
}[]
}

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeMain data={data} />
      <Footer/>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
